return

diff --git a/bash_scripts b/bash_scripts
--- a/bash_scripts
+++ b/bash_scripts
@@ -13,8 +13,10 @@ fi
 !
 -a and
 -o or
-|| or
-&& and
+|| command=1 echo error
+&& command=1 echo error
+firefox & in background mode
+command && echo true || echo false
 echo "88.8 < 77.8" | bc -l
 # 0
 echo $((2+2))
@@ -161,7 +163,45 @@ time — время отклика в миллисекундах (ms)
 for x in youtube.com google.com bing.com facebook.com networkchuck.com;
 do
         if ping -q -c 2 -W 1 $x > /dev/null;then
-                echo "$x is up"
+       #!/bin/bash
+
+file="processing.log"
+
+max_duration=0
+longest_video=""
+
+for video in $(grep "Начал обработку" "$file" | awk '{print $6}' | sort -u); do
+    # Находим время начала
+    start_time=$(grep "Начал обработку $video" "$file" | awk '{print $1,$2}')
+    
+    # Находим время окончания
+    end_time=$(grep "Завершено: $video" "$file" | awk '{print $1,$2}')
+    
+    # Проверяем, что оба времени найдены
+    if [ -z "$start_time" ] || [ -z "$end_time" ]; then
+        continue
+    fi
+    
+    # Преобразуем в секунды
+    start=$(date -d "$start_time" +%s)
+    end=$(date -d "$end_time" +%s)
+    
+    # Длительность
+    duration=$((end - start))
+    
+    # Сравниваем
+    if [ $duration -gt $max_duration ]; then
+        max_duration=$duration
+        longest_video=$video
+    fi
+done
+
+# Выводим результат
+if [ -n "$longest_video" ]; then
+    echo "$longest_video $max_duration"
+else
+    echo "Видео не найдено или не обработано"
+fi         echo "$x is up"
         else
                 echo $x is down
         fi
@@ -273,4 +313,24 @@ wget -O name_file - save how name
 $? code last command 0=true
 
 echo $(basename "$SHELL")
+
+file=app.log
+grep 2025-04-05 $file
+grep 2025-04-06 $file
+echo Morning:
+awk '$2 ~ /^08:/ || $2 ~ /^09:/' $file
+echo successfull:
+grep "Успех" $file | wc -l
+grep "ERROR" $file | awk '{print $1,$2}'
+echo modified: > summary.txt
+grep "Обработка" $file | wc -l >> summary.txt
+echo "Count of error:" >>summary.txt
+grep "ERROR" $file | wc -l >> summary.txt
+early=$(grep 'Скрипт запущен' $file | sort | head -1 | awk '{print $1,$2}')
+late=$(grep 'Скрипт запущен' $file | sort | tail -1 | awk '{print $1,$2}')
+echo early: $early >> summary.txt
+echo late: $late >> summary.txt
+
+date -d "2025-04-05 10:00:01" +%s - time start since start epoch
+%s     seconds since the Epoch (1970-01-01 00:00 UTC)
 
